name: Run tests for PR

on:  
  pull_request:
    branches:
      - master
    
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Use build.fsx
      run: dotnet fsi ./build.fsx -- -p test
